credentials:
  usernames:
    v1:
      email: "vinicius.torres@innovatismc.com"
      logged_in: False
      name: "Vinicius Torres"
      password: "191919"
    maysa:
      email: "contato@innovatismc.com"
      logged_in: False
      name: "Maysa Barreiro"
      password: "admin"
    epitacio:
      email: "epitacio@innovatismc.com"
      logged_in: False
      name: "Epitacio Brito"
      password: "HgEB1234***"
     clara:
      email: "clara.santos@innovatismc.com"
      logged_in: False
      name: "Clara Santos"
      password: "InnovaLabs86"
cookie:
  expiry_days: 30
  key: "some_signature_key"

  name: "some_cookie_name"
