name: Keep Streamlit Awake (00:00, 07:50, 18:50 Recife)

on:
  schedule:
    # 00:00 America/Recife (UTC-3) -> 03:00 UTC
    - cron: "0 3 * * *"
    # 07:50 America/Recife (UTC-3) -> 10:50 UTC
    - cron: "50 10 * * *"
    # 18:50 America/Recife (UTC-3) -> 21:50 UTC
    - cron: "50 21 * * *"
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: keepalive-empty-commit
  cancel-in-progress: false

jobs:
  keepalive:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout default branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Resolve default branch safely
        id: branch
        shell: bash
        run: |
          DEFAULT_BRANCH="${{ github.event.repository.default_branch }}"
          if [ -z "$DEFAULT_BRANCH" ]; then
            DEFAULT_BRANCH="$(git remote show origin | sed -n '/HEAD branch/s/.*: //p')"
          fi
          if [ -z "$DEFAULT_BRANCH" ]; then
            DEFAULT_BRANCH="main"
          fi
          echo "default_branch=$DEFAULT_BRANCH" >> "$GITHUB_OUTPUT"

      - name: Configure Git author (actions bot)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Create empty commit and push
        run: |
          BRANCH="${{ steps.branch.outputs.default_branch }}"
          git fetch origin "$BRANCH" --depth=1
          git checkout "$BRANCH"
          git pull --ff-only origin "$BRANCH" || true
          git commit --allow-empty -m "chore(keepalive): empty commit $(date -u +'%Y-%m-%dT%H:%M:%SZ') [skip ci]"
          git push origin HEAD:"$BRANCH"
